import { useEffect, useMemo, useState } from 'react';
import { recipes as libraryRecipes } from './data';
import { calculateGroceries } from './grocery';
import { createSamplePlanner, loadPlanner, savePlanner } from './storage';
import type { Meal, PantryEntry, PlannerState, Recipe } from './types';
import './styles.css';

type View = 'week' | 'pantry' | 'groceries';
const amount = (n: number | null) => n === null ? 'As needed' : Number(n.toFixed(2)).toString();
const uid = () => crypto.randomUUID();
interface PlannerProps {
  initialState?: PlannerState;
  account?: string;
  onSignIn?: () => void;
  onSignOut?: () => void;
  onSave?: (state: PlannerState) => void;
  onWeekChange?: (date: string) => void;
  saving?: boolean;
  cloudMessage?: string;
  cloudError?: boolean;
  onReload?: () => void;
}
export default function App(props: PlannerProps) {
  const [state, setState] = useState<PlannerState>(() => props.initialState ?? loadPlanner());
  const cloud = !!props.account;
  const dirty = cloud && JSON.stringify(state) !== JSON.stringify(props.initialState);
  const recipes = libraryRecipes;
  const leaveEdits = () => !dirty || window.confirm('You have unsaved changes. Discard them?');
  useEffect(() => {
    if (!dirty) return;
    const preventLoss = (e: BeforeUnloadEvent) => { e.preventDefault(); };
    window.addEventListener('beforeunload', preventLoss);
    return () => window.removeEventListener('beforeunload', preventLoss);
  }, [dirty]);
  const [view, setView] = useState<View>('week');
  const [picker, setPicker] = useState(false);
  const [search, setSearch] = useState('');
  const [newItem, setNewItem] = useState('');
  const [detail, setDetail] = useState<Recipe | null>(null);
  const [saveError, setSaveError] = useState(false);
  const [resetConfirm, setResetConfirm] = useState(false);
  useEffect(() => { if (cloud) return; try { savePlanner(state); setSaveError(false); } catch { setSaveError(true); } }, [state, cloud]);
  const modalOpen = picker || !!detail || resetConfirm;
  useEffect(() => {
    if (!modalOpen) return;
    const previous = document.activeElement as HTMLElement | null;
    const dialog = document.querySelector<HTMLElement>('[role="dialog"]');
    const focusables = () => Array.from(dialog?.querySelectorAll<HTMLElement>('button, input, select, a[href], [tabindex="0"]') ?? []).filter(el => !el.hasAttribute('disabled'));
    const initialFocus = dialog?.querySelector<HTMLElement>('input') ?? focusables()[0];
    initialFocus?.focus({ preventScroll: true });
    const handleKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { setPicker(false); setDetail(null); setResetConfirm(false); }
      if (event.key !== 'Tab') return;
      const elements = focusables();
      const first = elements[0], last = elements[elements.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    };
    const shell = document.querySelector<HTMLElement>('.app-shell');
    if (shell) shell.inert = true;
    document.addEventListener('keydown', handleKey);
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => { document.removeEventListener('keydown', handleKey); document.body.style.overflow = previousOverflow; if (shell) shell.inert = false; previous?.focus(); };
  }, [modalOpen]);
  const groceries = useMemo(() => calculateGroceries(recipes, state.meals, state.pantry), [state]);
  const needed = groceries.filter(i => i.status === 'needed');
  const review = groceries.filter(i => i.status === 'review');
  const covered = groceries.filter(i => i.status === 'covered');
  const selected = state.meals.map(meal => ({ meal, recipe: meal.recipeSnapshot ?? recipes.find(r => r.id === meal.recipeId) })).filter((x): x is { meal: Meal; recipe: Recipe } => !!x.recipe);
  const clearConfirmation = (pantry: PantryEntry[]) => pantry.map(p => ({ ...p, confirmedEnough: false }));
  const updateMeal = (id: string, changes: Partial<Meal>) => setState(s => ({ ...s, pantry: clearConfirmation(s.pantry), meals: s.meals.map(m => m.id === id ? { ...m, ...changes } : m) }));
  const updatePantry = (id: string, changes: Partial<PantryEntry>) => setState(s => ({ ...s, pantry: s.pantry.map(p => p.id === id ? { ...p, ...changes, updatedAt: new Date().toISOString() } : p) }));
  const addPantry = (name: string) => { if (!name.trim()) return; setState(s => s.pantry.some(p => p.name.toLowerCase() === name.trim().toLowerCase()) ? s : ({ ...s, pantry: [...s.pantry, { id: uid(), name: name.trim(), status: 'have', updatedAt: new Date().toISOString() }] })); setNewItem(''); };
  const dateLabel = new Date(`${state.weekOf}T12:00:00`).toLocaleDateString('en-US', { month: 'long', day: 'numeric' });
  const exportList = () => { const text = [`WEEKNIGHT — Week of ${dateLabel}`, '', ...selected.map(({ meal, recipe }) => `${recipe.name} · ${meal.servings} servings`), '', 'GROCERIES', ...groceries.map(i => `${i.status === 'covered' ? '[covered]' : '[ ]'} ${i.name}: ${amount(i.shortage)} ${i.unit} ${i.status === 'review' ? '(review needed)' : ''}`)].join('\n'); const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = `weeknight-${state.weekOf}.txt`; a.click(); URL.revokeObjectURL(url); };
  return <>
    <div className="app-shell no-print">
      <header className="topbar"><a className="brand" href="#" onClick={e => { e.preventDefault(); setView('week'); }}><span className="brand-icon">w.</span>weeknight<span className="brand-dot">●</span></a><div className="topbar-right"><span className="sample-pill"><span />{cloud ? props.account : 'Sample household'}</span>{cloud ? <button className="text-button" disabled={props.saving} onClick={() => { if (leaveEdits()) props.onSignOut?.(); }}>Sign out</button> : <><button className="text-button" onClick={() => setResetConfirm(true)}>Reset sample</button>{props.onSignIn && <button className="button primary compact" onClick={props.onSignIn}>Sign in</button>}</>}</div></header>
      <div className="workspace"><aside className="sidebar"><p className="eyebrow">A little planning.<br />A better week.</p><nav aria-label="Main navigation">{([['week', '01', 'This week'], ['pantry', '02', 'Your pantry'], ['groceries', '03', 'Grocery review']] as const).map(([key, num, label]) => <button key={key} className={`nav-item ${view === key ? 'active' : ''}`} onClick={() => setView(key)} aria-current={view === key ? 'page' : undefined}><span>{num}</span>{label}{key === 'groceries' && <small>{needed.length + review.length}</small>}</button>)}</nav><div className="sidebar-note"><span className="small-sprout">✳</span><h3>Use what you have.</h3><p>A quick pantry check means fewer duplicate groceries and an easier shop.</p><button className="text-button" onClick={() => setView('pantry')}>Check your pantry ↗</button></div><p className="storage-note" role="status">{cloud ? (props.cloudMessage || (dirty ? 'Unsaved changes' : 'Saved to your account')) : saveError ? 'Changes could not be saved. Keep this tab open and export your list.' : 'Saved in this browser'}<br /><span>{cloud ? 'Private household · save before switching weeks' : 'Sample mode · no account required'}</span></p></aside>
      <main id="main-content">
        <div className="page-heading"><div><p className="eyebrow">YOUR WEEKNIGHT, SIMPLIFIED</p><h1>{view === 'week' ? 'Good meals. Less guesswork.' : view === 'pantry' ? 'Start with what’s here.' : 'A little list. A lighter week.'}</h1><p className="subtitle">{view === 'week' ? 'Pick a few favorites. We’ll help with the grocery list.' : view === 'pantry' ? 'No inventory spreadsheets. Just a quick check of the essentials.' : 'Your meals, minus what’s already in your kitchen.'}</p></div><span className="heading-flower" aria-hidden="true">✳</span></div>
        <div className="week-toolbar"><label className="week-date">Week of <input aria-label="Plan week date" type="date" value={state.weekOf} disabled={props.saving} onChange={e => { if (!e.target.value) return; if (cloud) { if (leaveEdits()) props.onWeekChange?.(e.target.value); } else setState(s => ({ ...s, weekOf: e.target.value, pantry: clearConfirmation(s.pantry) })); }} /></label><span className="subtle">{cloud ? 'Weekly plans saved to your account' : 'One plan saved locally'}</span>{cloud && <button className="button primary compact" disabled={props.saving || props.cloudError || !dirty} onClick={() => props.onSave?.(state)}>{props.saving ? 'Saving…' : dirty ? 'Save changes' : 'Saved'}</button>}<button className="button secondary compact" onClick={() => window.print()}>↗ Print week</button></div>
        {cloud && props.cloudMessage && <div className="cloud-notice" role={props.cloudError ? 'alert' : 'status'}>{props.cloudMessage}{props.cloudError && <button className="button secondary compact" onClick={() => { if (leaveEdits()) props.onReload?.(); }}>Reload saved data</button>}</div>}
        <fieldset className="planner-editing" disabled={props.saving}>
        {view === 'week' && <div className="plan-layout"><section><div className="section-heading"><h2>On the menu <span>{selected.length}</span></h2><button className="text-button" onClick={() => setPicker(true)}>+ Add a meal</button></div><div className="meal-list">{selected.map(({ meal, recipe }, index) => <article className="meal-card" key={meal.id}><div className={`meal-art art-${index % 4}`} aria-hidden="true"><span className="plate"><span>{['◒', '✳', '❋', '◉'][index % 4]}</span></span><span className="art-caption">DINNER {String(index + 1).padStart(2, '0')}</span></div><div className="meal-content"><div className="meal-meta"><span>{recipe.bucketLabel}</span><span>{recipe.time} min</span></div><button className="recipe-title" onClick={() => setDetail(recipe)}>{recipe.name}</button><p>{recipe.description}</p><div className="meal-controls"><label>Servings <input aria-label={`Servings for ${recipe.name}`} type="number" min="1" max="24" value={meal.servings} onChange={e => updateMeal(meal.id, { servings: Math.max(1, Math.min(24, Number(e.target.value) || 1)) })} /></label><button className="text-button muted" aria-label={`Remove ${recipe.name}`} onClick={() => setState(s => ({ ...s, pantry: clearConfirmation(s.pantry), meals: s.meals.filter(m => m.id !== meal.id) }))}>Remove</button></div>{!!recipe.proteins?.length && <label className="protein-select">Add a protein<select value={meal.proteinIndex ?? ''} onChange={e => updateMeal(meal.id, { proteinIndex: e.target.value === '' ? undefined : Number(e.target.value) })}><option value="">No extra protein</option>{recipe.proteins.map((p, i) => <option value={i} key={p.name}>{p.name}</option>)}</select></label>}</div></article>)}<button className="add-meal-card" onClick={() => setPicker(true)}><span>+</span><strong>{selected.length ? 'Room for another favorite?' : 'What sounds good this week?'}</strong><small>Explore your recipe collection</small></button></div></section><aside className="grocery-summary"><p className="eyebrow">FROM PLAN TO PANTRY</p><h2>Your grocery<br />list is taking shape.</h2><p>Every meal comes together in one list, with pantry items accounted for.</p><div className="summary-count"><strong>{needed.length + review.length}</strong><span>items to shop or review</span></div><div className="summary-row"><span>Covered by your pantry</span><strong>{covered.length}</strong></div><div className="summary-row"><span>Need a quick check</span><strong>{review.length}</strong></div><button className="button primary full" onClick={() => setView('groceries')}>Review groceries <span>→</span></button><p className="fine-print">You’re in control. Nothing is purchased or sent to a store.</p><div className="little-tip"><span>✳</span><p><strong>A good place to start</strong>Three dinners leave room for leftovers, a spontaneous evening, and life.</p></div></aside></div>}
        {view === 'pantry' && <section><div className="pantry-intro"><p><strong>Keep it simple.</strong> Mark what you have, what’s low, and what’s out. Add amounts only when useful. Confirm there’s enough before we leave an item off your list.</p></div><form className="pantry-add" onSubmit={e => { e.preventDefault(); addPantry(newItem); }}><label className="sr-only" htmlFor="pantry-name">Pantry ingredient</label><input id="pantry-name" value={newItem} onChange={e => setNewItem(e.target.value)} placeholder="Add an ingredient, e.g. olive oil" required /><button className="button primary" type="submit">+ Add item</button></form><div className="section-heading"><h2>Your kitchen <span>{state.pantry.length}</span></h2></div><div className="pantry-list">{state.pantry.map(p => <article className="pantry-card" key={p.id}><div className="pantry-name"><h3>{p.name}</h3><small>Checked {new Date(p.updatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</small></div><div className="pantry-status" role="group" aria-label={`Status of ${p.name}`}>{([['have', 'Have it'], ['low', 'Running low'], ['out', 'Out']] as const).map(([value, label]) => <button key={value} aria-pressed={p.status === value} className={p.status === value ? `selected ${value}` : ''} onClick={() => updatePantry(p.id, { status: value, quantity: value === 'out' ? undefined : p.quantity, unit: value === 'out' ? undefined : p.unit, confirmedEnough: false })}>{label}</button>)}</div><div className="pantry-details"><label>Amount <input type="number" min="0" step="any" placeholder="Optional" aria-label={`Amount of ${p.name}`} value={p.quantity ?? ''} onChange={e => updatePantry(p.id, { quantity: e.target.value === '' ? undefined : Math.max(0, Number(e.target.value)), confirmedEnough: false })} /></label><label>Unit <input placeholder="e.g. g, cup" aria-label={`Unit for ${p.name}`} value={p.unit ?? ''} onChange={e => updatePantry(p.id, { unit: e.target.value, confirmedEnough: false })} /></label>{p.status === 'have' && p.quantity === undefined && <label className="check-label"><input type="checkbox" checked={!!p.confirmedEnough} onChange={e => updatePantry(p.id, { confirmedEnough: e.target.checked })} />Enough for this plan</label>}<button className="text-button muted" aria-label={`Delete ${p.name} from pantry`} onClick={() => setState(s => ({ ...s, pantry: s.pantry.filter(x => x.id !== p.id) }))}>Remove</button></div></article>)}</div>{!state.pantry.length && <p className="empty-state">Start with the ingredients you reach for most. You can also add pantry items from grocery review.</p>}<div className="bottom-action"><button className="button primary" onClick={() => setView('groceries')}>Review my groceries →</button></div></section>}
        {view === 'groceries' && <section><div className="grocery-stats"><div><strong>{needed.length}</strong><span>To buy</span></div><div><strong>{review.length}</strong><span>To check</span></div><div><strong>{covered.length}</strong><span>Already covered</span></div><button className="button secondary compact" onClick={exportList}>↓ Export list</button></div>{!groceries.length && <div className="empty-state">Your grocery list starts with a meal.<br /><button className="button primary" onClick={() => { setView('week'); setPicker(true); }}>Choose meals</button></div>}{([{ title: 'Needs a quick check', items: review, kind: 'review', description: 'Confirm pantry amounts or check ingredients with unspecified quantities.' }, { title: 'On your shopping list', items: needed, kind: 'needed', description: 'Amounts still needed after accounting for your pantry.' }, { title: 'Covered by your pantry', items: covered, kind: 'covered', description: 'Already on hand for this plan.' }]).filter(g => g.items.length).map(group => <section className={`grocery-group ${group.kind}`} key={group.kind}><div className="section-heading"><h2>{group.title} <span>{group.items.length}</span></h2></div><p className="group-description">{group.description}</p>{group.items.map(item => <article className="grocery-item" key={item.id}><span className="grocery-indicator" aria-hidden="true">{item.status === 'covered' ? '✓' : item.status === 'review' ? '?' : '○'}</span><div className="grocery-name"><h3>{item.name}</h3><p>{item.meals.join(' · ')}</p>{item.status === 'review' && <small>{item.reasons.join(' ')}</small>}</div><div className="grocery-quantity">{amount(item.shortage)} {item.shortage !== null && item.unit}<small>{item.covered > 0 ? `${amount(item.covered)} ${item.unit} from pantry` : item.category}</small></div>{item.status !== 'covered' && <button className="text-button" onClick={() => { addPantry(item.name); setView('pantry'); }}>Check pantry ↗</button>}</article>)}</section>)}<div className="shopping-note"><span>↗</span><div><h3>Ready for your usual grocery run.</h3><p>Print or export this list. Store connection and cart building are coming in a later milestone.</p></div><button className="button primary" onClick={() => window.print()}>Print week</button></div></section>}
        </fieldset><footer>Less planning. More around the table.<span>{cloud ? 'weeknight / your household' : 'weeknight / sample edition'}</span></footer>
      </main></div>
    </div>
    {picker && <div className="modal-backdrop no-print" onMouseDown={e => { if (e.target === e.currentTarget) setPicker(false); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="picker-title" onClick={e => e.stopPropagation()} onKeyDown={e => { if (e.key === 'Escape') setPicker(false); }}><div className="section-heading"><div><p className="eyebrow">MAKE ROOM FOR SOMETHING GOOD</p><h2 id="picker-title">Find your next dinner.</h2></div><button className="close-button" aria-label="Close recipe picker" onClick={() => setPicker(false)}>×</button></div><input className="search-input" autoFocus placeholder="Search recipes or ingredients…" aria-label="Search recipes" value={search} onChange={e => setSearch(e.target.value)} /><div className="recipe-results">{recipes.filter(r => `${r.name} ${r.ingredients.map(i => i.name).join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(r => <article key={r.id}><div><small>{r.bucketLabel} · {r.time} min</small><h3>{r.name}</h3><p>{r.description}</p></div><button className="button secondary compact" onClick={() => { setState(s => ({ ...s, pantry: clearConfirmation(s.pantry), meals: [...s.meals, { id: uid(), recipeId: r.id, servings: r.servings, recipeSnapshot: structuredClone(r) }] })); setPicker(false); setSearch(''); }}>+ Add</button></article>)}</div></section></div>}
    {detail && <div className="modal-backdrop no-print" onMouseDown={e => { if (e.target === e.currentTarget) setDetail(null); }}><section className="modal recipe-detail" role="dialog" aria-modal="true" aria-labelledby="detail-title" onClick={e => e.stopPropagation()} onKeyDown={e => { if (e.key === 'Escape') setDetail(null); }}><div className="section-heading"><h2 id="detail-title">{detail.name}</h2><button autoFocus className="close-button" aria-label="Close recipe" onClick={() => setDetail(null)}>×</button></div><p>{detail.time} minutes · Original recipe serves {detail.servings}</p><h3>Ingredients</h3><ul>{detail.ingredients.map(i => <li key={i.id}>{amount(i.amount)} {i.unit} {i.name}</li>)}</ul><h3>Method</h3><ol>{detail.steps.map((step, i) => <li key={i}>{step}</li>)}</ol></section></div>}
    {resetConfirm && <div className="modal-backdrop no-print"><section className="modal small-modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><h2 id="reset-title">Start fresh?</h2><p>This replaces the plan and pantry saved in this browser with the sample household.</p><div className="bottom-action"><button autoFocus className="button secondary" onClick={() => setResetConfirm(false)}>Keep my plan</button><button className="button primary" onClick={() => { setState(createSamplePlanner()); setResetConfirm(false); }}>Reset sample</button></div></section></div>}
    <div className="print-only"><h1>Weeknight</h1><p>Week of {dateLabel} · {selected.length} dinners</p><h2>Shopping list</h2>{groceries.filter(i => i.status !== 'covered').map(i => <p key={i.id}>□ {i.name} — {amount(i.shortage)} {i.shortage !== null && i.unit}{i.status === 'review' ? ` · CHECK: ${i.reasons.join(' ')}` : ''}</p>)}{covered.length > 0 && <p>Covered by pantry: {covered.map(i => i.name).join(', ')}</p>}{selected.map(({ meal, recipe }) => <section className="print-recipe" key={meal.id}><h2>{recipe.name}</h2><p>{recipe.time} minutes · {meal.servings} servings</p><ul>{recipe.ingredients.map(i => <li key={i.id}>{amount(i.amount === null ? null : i.amount * meal.servings / recipe.servings)} {i.unit} {i.name}</li>)}</ul>{meal.proteinIndex !== undefined && recipe.proteins?.[meal.proteinIndex] && <p><strong>Protein:</strong> {recipe.proteins[meal.proteinIndex].name} · Base recipe amount: {recipe.proteins[meal.proteinIndex].amount}. Scale by {amount(meal.servings / recipe.servings)}×. {recipe.proteins[meal.proteinIndex].instructions}</p>}<ol>{recipe.steps.map((step, i) => <li key={i}>{step}</li>)}</ol></section>)}</div>
  </>;
}
